language: php

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.6

matrix:
    include:
        - php: 5.4
          dist: trusty
        - php: 5.5
          dist: trusty
          env: PHPUNIT_VERSION="^4.8"
        - php: 7.0
          env: PHPUNIT_VERSION="^6.5"
        - php: 7.1
          env: PHPUNIT_VERSION="^7.2"
        - php: 7.2
          env: PHPUNIT_VERSION="^7.2"
        - php: 7.3
          env: PHPUNIT_VERSION="^7.2"
        - php: 7.4
          env: PHPUNIT_VERSION="^7.2"

before_install:
    - composer config -g github-oauth.github.com 8a184177873281ce443912bd9f8fc4a959f7e7bb
    - composer require satooshi/php-coveralls:^1.0 --no-update

install:
    - composer update --prefer-dist --no-interaction
    - if [ "$PHPUNIT_VERSION" != "" ]; then composer global require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-interaction; fi;

before_script:
    - mkdir -p build/logs
    - DEPENDENCY_BINARY_FOLDER=`composer global config bin-dir --absolute --quiet`

script:
    - if [ "$PHPUNIT_VERSION" != "" ]; then XDEBUG_MODE=coverage ${DEPENDENCY_BINARY_FOLDER}/phpunit --coverage-clover build/logs/clover.xml; fi;
    - if [ "$PHPUNIT_VERSION" = "" ]; then XDEBUG_MODE=coverage phpunit --coverage-clover build/logs/clover.xml; fi;

after_script:
    - php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar -t 3
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
